#!/bin/bash

./miri_tests &&
cargo bench --no-run &&
RUSTFLAGS="--cfg bench" cargo +nightly bench --no-run &&
RUSTFLAGS="--cfg examples" cargo build --example simple &&
cd .. && MIRIFLAGS="-Zmiri-disable-isolation ${MIRIFLAGS:-}" cargo +nightly miri run --example concurrent
