#!/bin/bash

./miri_tests &&
cargo test --test tests test_multi_thread_rayon &&
cargo bench --no-run &&
RUSTFLAGS="--cfg examples" cargo build --example simple &&
cd .. && MIRIFLAGS="-Zmiri-disable-isolation ${MIRIFLAGS:-}" cargo +nightly miri run --example concurrent
