name: Rust + Miri

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install fontconfig
      run: sudo apt-get -y install libfontconfig1-dev
    - name: Install Miri
      run:  |
        rustup toolchain install nightly --component miri
        rustup override set nightly
        cargo miri setup
    - name: Run tests
      run: cd ./scripts && ./dev_run_before_push
